<script setup>
import { onMounted, reactive, ref } from 'vue'; import axios from 'axios'; import PageHeader from '../components/PageHeader.vue';
const devices = ref([]); const token = ref(''); const message = ref('');
const form = reactive({ name: 'Main Gate Face Terminal', type: 'facial', location: 'Main entrance', provider: 'Nenial Browser Terminal', external_id: '' });
async function load() { devices.value = (await axios.get('/api/devices')).data; } onMounted(load);
async function create() { try { const { data } = await axios.post('/api/devices', form); token.value = data.token; message.value = 'Device registered. Copy its token now—it is shown only once.'; await load(); } catch (error) { message.value = error.response?.data?.message || 'Unable to register device.'; } }
async function removeDevice(device) { if (!confirm(`Remove ${device.name}? Its token will stop working immediately.`)) return; try { await axios.delete(`/api/devices/${device.id}`); message.value = `${device.name} removed.`; await load(); } catch (error) { message.value = error.response?.data?.message || 'Unable to remove device.'; } }
</script>

<template>
    <PageHeader title="Store devices" subtitle="Register and monitor barcode, POS, and facial-recognition hardware"><RouterLink class="btn primary" to="/face-terminal">Open face terminal</RouterLink></PageHeader>
    <p v-if="message" class="notice">{{ message }}</p>
    <div v-if="token" class="secret"><strong>One-time device token</strong><code>{{ token }}</code><button class="btn" @click="navigator.clipboard.writeText(token)">Copy token</button></div>
    <div class="two-col">
        <section class="panel"><div class="panel-head"><h2>Register hardware</h2></div><form class="stack" @submit.prevent="create"><label>Name<input v-model="form.name" required placeholder="Example: Owner's Realme 7 Pro"></label><label>Type<select v-model="form.type"><option value="facial">Computer facial terminal</option><option value="facial_mobile">Mobile-phone facial terminal</option><option value="barcode">Barcode scanner</option><option value="pos">POS terminal</option></select></label><label>Location<input v-model="form.location" placeholder="Entrance, counter, warehouse"></label><label>Provider / model<input v-model="form.provider" placeholder="Nenial Mobile, Zebra DS2208, etc."></label><label>External device ID<input v-model="form.external_id" placeholder="Optional unique serial number"></label><button class="btn primary">Generate device token</button></form></section>
        <section class="panel"><div class="panel-head"><h2>Registered devices</h2><span class="live">● Monitoring</span></div><div v-for="device in devices" :key="device.id" class="device"><div><strong>{{ device.name }}</strong><small>{{ device.type.replace('_', ' ') }} · {{ device.location || 'No location' }}</small></div><div class="device-actions"><span class="tag" :class="{ warn: !device.last_seen_at }">{{ device.last_seen_at ? `Seen ${new Date(device.last_seen_at).toLocaleString()}` : 'Never connected' }}</span><button class="btn tiny danger" @click="removeDevice(device)">Remove</button></div></div><div v-if="!devices.length" class="empty">No devices registered.</div></section>
    </div>
    <section class="panel guide"><div class="panel-head"><div><h2>Detailed hardware setup</h2><small>Complete these checks before using a device for live transactions or attendance.</small></div></div><div class="guide-grid">
        <article><h3>USB or Bluetooth barcode scanner</h3><ol><li>Connect the scanner by USB, or pair it through Bluetooth.</li><li>Use its manual to select <strong>HID Keyboard Mode</strong>, not serial/COM mode.</li><li>Scan the configuration barcode for an <strong>Enter/CR suffix</strong>.</li><li>Match its keyboard country/layout to Windows.</li><li>Open POS Terminal, tap the barcode field, and scan a barcode stored in Inventory.</li><li>Confirm the correct product is added once. Test ten scans and one unknown barcode.</li><li>If it types but does not submit, re-enable Enter/CR. If nothing appears, check HID mode.</li></ol></article>
        <article><h3>Computer facial terminal</h3><ol><li>Assign every employee a unique Face Subject ID in Workforce.</li><li>Register a Computer facial terminal and copy the one-time token.</li><li>On that computer open <code>http://localhost:8080/face-terminal</code>.</li><li>Paste the token, allow camera access, and start the camera.</li><li>Select a consenting employee and capture the five guided samples.</li><li>For attendance, face the camera and hold still until identity is confirmed.</li><li>Verify the U.S.-formatted date and time under Workforce → Attendance.</li></ol></article>
        <article><h3>Mobile-phone facial terminal</h3><ol><li>Register a Mobile-phone facial terminal and copy its token.</li><li>On the phone use the deployed HTTPS address, such as <code>https://nenialsync.vercel.app/face-terminal</code>. Ordinary LAN HTTP cannot access a phone camera.</li><li>In Chrome choose Add to Home screen or Install app.</li><li>Open it, paste the token, allow camera permission, and use the front camera.</li><li>Enroll employees once. Shared descriptors synchronize with authorized online and offline terminals.</li><li>Disable battery optimization for the PWA, keep the phone charged, and mount it at eye level.</li><li>For offline mobile attendance, configure trusted HTTPS on the local server.</li></ol></article>
        <article><h3>Troubleshooting and safety</h3><ol><li>If permission was denied, change Camera to Allow in browser Site settings.</li><li>If matching is unreliable, remove and repeat enrollment in even front lighting.</li><li>The terminal confirms identity over several steady frames; use a depth/IR terminal for higher anti-spoofing security.</li><li>Remove a mistaken device here. Its bearer token becomes invalid immediately.</li><li>Obtain consent and maintain a biometric retention and deletion policy.</li></ol></article>
    </div></section>
</template>
