<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue'; import axios from 'axios'; import PageHeader from '../components/PageHeader.vue'; import { useAuthStore } from '../stores/auth';
const auth = useAuthStore(); const orders = ref([]); const message = ref('');
let refreshTimer; let loading = false;
async function load() { if (loading) return; loading = true; try { orders.value = (await axios.get('/api/orders')).data.data; } catch { /* Keep the last good order list visible. */ } finally { loading = false; } }
onMounted(() => { load(); refreshTimer = window.setInterval(load, 3000); });
onBeforeUnmount(() => window.clearInterval(refreshTimer));
async function status(order, value) { try { await axios.put(`/api/orders/${order.id}/status`, { status: value }); await load(); } catch (error) { message.value = error.response?.data?.message || 'Update failed.'; } }
async function receive(order) { if (!confirm('Confirm all materials were received and release payment?')) return; await axios.post(`/api/orders/${order.id}/receive`); await load(); }
async function cancel(order) { if (!confirm('Cancel this order and release reserved inventory?')) return; await axios.post(`/api/orders/${order.id}/cancel`); await load(); }
</script>
<template><PageHeader :title="auth.role === 'user' ? 'My orders' : 'Order fulfillment'" subtitle="Protected payments and inventory reservations"/><p v-if="message" class="notice">{{ message }}</p><section class="panel table-wrap"><table><thead><tr><th>Reference</th><th>Customer</th><th>Items</th><th>Total</th><th>Delivery</th><th>Payment</th><th>Action</th></tr></thead><tbody>
    <tr v-for="order in orders" :key="order.id"><td data-label="Reference"><strong>{{ order.reference }}</strong><small>{{ new Date(order.created_at).toLocaleString() }}</small></td><td data-label="Customer">{{ order.customer?.name }}</td><td data-label="Items">{{ order.items.map(item => `${item.product_name} × ${item.quantity}`).join(', ') }}</td><td data-label="Total">₱{{ Number(order.total).toLocaleString() }}</td><td data-label="Delivery"><span class="tag">{{ order.status }}</span></td><td data-label="Payment"><span class="tag" :class="{ warn: order.payment_status !== 'paid' }">{{ order.payment_status }}</span></td><td data-label="Actions"><div class="actions"><button v-if="['admin','assistant'].includes(auth.role) && order.status === 'preparing'" class="btn tiny" @click="status(order, 'dispatched')">Dispatch</button><button v-if="['admin','assistant'].includes(auth.role) && order.status === 'dispatched'" class="btn tiny primary" @click="status(order, 'delivered')">Delivered</button><button v-if="auth.role === 'user' && order.status === 'delivered'" class="btn tiny primary" @click="receive(order)">Confirm receipt</button><button v-if="['preparing','dispatched'].includes(order.status) && (auth.role === 'admin' || auth.role === 'user')" class="btn tiny danger" @click="cancel(order)">Cancel</button></div></td></tr>
    <tr v-if="!orders.length" class="empty-row"><td colspan="7"><div class="empty">No orders yet.</div></td></tr>
</tbody></table></section></template>
