<script setup>
import{computed,onBeforeUnmount,onMounted,ref}from'vue';import axios from'axios';import{BrowserMultiFormatReader}from'@zxing/browser';import PageHeader from'../components/PageHeader.vue';import{useInventoryStore}from'../stores/inventory';
const inventory=useInventoryStore(),search=ref(''),barcode=ref(''),cart=ref([]),message=ref(''),busy=ref(false),showCamera=ref(false),video=ref(null),reader=new BrowserMultiFormatReader();let scannerControls=null,checkoutKey=crypto.randomUUID();
const products=computed(()=>inventory.products.filter(p=>[p.name,p.sku,p.barcode].some(v=>v.toLowerCase().includes(search.value.toLowerCase()))));const total=computed(()=>cart.value.reduce((s,i)=>s+i.price*i.quantity*(1-i.discount_percent/100),0));
onMounted(async()=>{await inventory.load();inventory.start()});onBeforeUnmount(()=>{inventory.stop();scannerControls?.stop()});
function add(p){const i=cart.value.find(x=>x.id===p.id),qty=(i?.quantity||0)+1;if(qty>p.available_quantity)return message.value='Insufficient available stock.';i?i.quantity++:cart.value.push({...p,quantity:1});barcode.value='';}
function scan(){const code=barcode.value.trim();const p=inventory.products.find(x=>x.barcode===code||x.sku.toLowerCase()===code.toLowerCase());p?add(p):message.value='Barcode or SKU not found.';}
function closeCamera(){scannerControls?.stop();scannerControls=null;showCamera.value=false}async function camera(){showCamera.value=true;await new Promise(r=>setTimeout(r));try{scannerControls=await reader.decodeFromVideoDevice(undefined,video.value,(result)=>{if(result){barcode.value=result.getText();closeCamera();scan();}})}catch{closeCamera();message.value='Camera access failed. Use a USB scanner or grant camera permission.'}}
async function checkout(){busy.value=true;try{const{data}=await axios.post('/api/pos/checkout',{items:cart.value.map(i=>({product_id:i.id,quantity:i.quantity})),payment_method:'cash',idempotency_key:checkoutKey});message.value=`Sale ${data.reference} completed · ₱${Number(data.total).toLocaleString()}`;cart.value=[];checkoutKey=crypto.randomUUID();await inventory.load()}catch(e){message.value=e.response?.data?.message||Object.values(e.response?.data?.errors||{})[0]?.[0]||'Sale failed.'}finally{busy.value=false}}
</script>
<template><PageHeader title="POS Terminal" subtitle="Fast counter checkout with transaction-safe stock deduction"><span class="live">● Inventory live</span></PageHeader><p v-if="message" class="notice">{{message}}</p><div class="pos-layout"><section class="panel compact-products"><div class="panel-head"><h2>Product keys</h2><span>{{products.length}} items</span></div><div class="scanner"><input v-model="barcode" @keyup.enter="scan" autofocus placeholder="Scan barcode or enter SKU"><button class="btn primary" @click="scan">Add</button><button class="btn ghost" @click="camera">Use camera</button></div><input v-model="search" class="search" placeholder="Search products"><div class="pos-keys"><button v-for="p in products" :key="p.id" :disabled="!p.available_quantity" @click="add(p)"><strong>{{p.name}}</strong><small>{{p.sku}} · {{p.available_quantity}} {{p.unit}}</small><b>₱{{Number(p.price).toLocaleString()}}</b></button></div></section><section class="panel sale-ticket"><div class="ticket-head"><div><small>REGISTER 01</small><h2>Sale Ticket</h2></div><span>{{cart.reduce((s,i)=>s+i.quantity,0)}} items</span></div><div class="ticket-lines"><div v-if="!cart.length" class="empty">Scan or select products to begin a sale.</div><div v-for="i in cart" :key="i.id" class="ticket-line"><div><strong>{{i.name}}</strong><small>₱{{i.price}} × {{i.quantity}}</small></div><div class="qty"><button @click="i.quantity>1?i.quantity--:cart.splice(cart.indexOf(i),1)">−</button><span>{{i.quantity}}</span><button :disabled="i.quantity>=i.available_quantity" @click="i.quantity++">+</button></div><b>₱{{(i.price*i.quantity*(1-i.discount_percent/100)).toLocaleString()}}</b></div></div><div class="ticket-total"><span>Total</span><strong>₱{{total.toLocaleString(undefined,{maximumFractionDigits:2})}}</strong></div><button class="btn primary full checkout" :disabled="!cart.length||busy" @click="checkout">{{busy?'Processing…':'Complete cash sale'}}</button></section></div><div v-if="showCamera" class="modal"><div class="modal-card"><div class="panel-head"><h2>Camera barcode scanner</h2><button class="btn ghost" @click="closeCamera">Close</button></div><video ref="video"></video><p>Position the barcode inside the camera view.</p></div></div></template>
