<script setup>
import { onMounted, ref } from 'vue';
import axios from 'axios';
import PageHeader from '../components/PageHeader.vue';
const data = ref({});
const from = ref(new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10));
const to = ref(new Date().toISOString().slice(0, 10));
const search = ref('');
async function load() { data.value = (await axios.get('/api/reports', { params: { from: from.value, to: to.value, search: search.value } })).data; }
onMounted(load);
function csv() { const rows = [['NENIAL REPORT'], ['From', from.value], ['To', to.value], [], ['Sales total', data.value.sales?.total], ['VATable sales', data.value.sales?.vatable_sales], ['VAT 12%', data.value.sales?.vat_amount], ['Transactions', data.value.sales?.count], [], ['Product', 'On hand', 'Reserved', 'Available'], ...(data.value.inventory || []).filter(product => product.name.toLowerCase().includes(search.value.toLowerCase())).map(product => [product.name, product.stock_quantity, product.reserved_quantity, product.available_quantity])]; const blob = new Blob([rows.map(row => row.map(value => `"${value ?? ''}"`).join(',')).join('\n')], { type: 'text/csv' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'nenial-report.csv'; link.click(); URL.revokeObjectURL(link.href); }
</script>
<template><PageHeader title="Company reports" subtitle="Daily, weekly, monthly, or custom operational reporting"><button class="btn primary" @click="csv">Download CSV</button></PageHeader><section class="panel filters"><label>From<input v-model="from" type="date"></label><label>To<input v-model="to" type="date"></label><label>Search<input v-model="search" placeholder="Product or detail"></label><button class="btn primary" @click="load">Apply</button></section><div class="stat-grid"><article class="stat"><span>Sales</span><strong>₱{{ Number(data.sales?.total || 0).toLocaleString() }}</strong><small>{{ data.sales?.count || 0 }} transactions</small></article><article class="stat"><span>VAT collected</span><strong>₱{{ Number(data.sales?.vat_amount || 0).toLocaleString() }}</strong><small>VATable sales ₱{{ Number(data.sales?.vatable_sales || 0).toLocaleString() }}</small></article><article class="stat"><span>Payroll</span><strong>₱{{ Number(data.payroll || 0).toLocaleString() }}</strong><small>Net payroll finalized</small></article><article class="stat"><span>Inventory</span><strong>{{ data.inventory?.length || 0 }}</strong><small>Tracked SKUs</small></article></div><section class="panel table-wrap"><div class="panel-head"><h2>Inventory report</h2></div><table><thead><tr><th>Product</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Value</th></tr></thead><tbody><tr v-for="product in (data.inventory || []).filter(item => item.name.toLowerCase().includes(search.toLowerCase()))" :key="product.id"><td>{{ product.name }}</td><td>{{ product.stock_quantity }}</td><td>{{ product.reserved_quantity }}</td><td>{{ product.available_quantity }}</td><td>₱{{ (product.stock_quantity * product.price).toLocaleString() }}</td></tr></tbody></table></section></template>
