<script setup>
import { computed, onMounted, ref } from 'vue';
import axios from 'axios';
import PageHeader from '../components/PageHeader.vue';

const data = ref({});
const from = ref(new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10));
const to = ref(new Date().toISOString().slice(0, 10));
const search = ref('');
const filteredInventory = computed(() => (data.value.inventory || []).filter(item => `${item.name} ${item.sku} ${item.category}`.toLowerCase().includes(search.value.toLowerCase())));
const money = value => Number(value || 0).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const dateTime = value => value ? new Date(value).toLocaleString('en-US', { timeZone: 'Asia/Manila' }) : '—';
async function load() { data.value = (await axios.get('/api/reports', { params: { from: from.value, to: to.value } })).data; }
onMounted(load);
function csv() {
    const rows = [
        ['NENIAL COMPANY REPORT'], ['From', from.value], ['To', to.value], [],
        ['Sales total', data.value.sales?.total], ['VATable sales', data.value.sales?.vatable_sales], ['VAT collected', data.value.sales?.vat_amount], ['Transactions', data.value.sales?.count],
        ['Orders', data.value.orders_summary?.count], ['Open orders', data.value.orders_summary?.pending], ['Attendance records', data.value.attendance_summary?.records], ['Employees represented', data.value.attendance_summary?.employees],
        ['Active employees', data.value.employees?.active], ['Finalized payroll net', data.value.payroll?.net_total], ['Inventory value', data.value.inventory_summary?.value], ['Low-stock products', data.value.inventory_summary?.low_stock],
        [], ['ORDER STATUS', 'Count', 'Value'], ...(data.value.orders || []).map(row => [row.status, row.count, row.total]),
        [], ['ATTENDANCE STATUS', 'Count'], ...(data.value.attendance || []).map(row => [row.status, row.count]),
        [], ['PAYROLL RUN', 'Period start', 'Period end', 'Employees', 'Gross', 'Net', 'Finalized'], ...(data.value.payroll?.runs || []).map(run => [run.reference, run.period_start, run.period_end, run.items_count, run.gross_pay, run.net_pay, run.finalized_at]),
        [], ['PRODUCT', 'SKU', 'On hand', 'Reserved', 'Available', 'Value'], ...filteredInventory.value.map(product => [product.name, product.sku, product.stock_quantity, product.reserved_quantity, product.available_quantity, product.stock_quantity * product.price]),
    ];
    const blob = new Blob([rows.map(row => row.map(value => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')).join('\n')], { type: 'text/csv' });
    const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `nenial-company-report-${from.value}-to-${to.value}.csv`; link.click(); URL.revokeObjectURL(link.href);
}
</script>

<template><PageHeader title="Company reports" subtitle="Sales, orders, attendance, payroll, workforce, and inventory in one report"><button class="btn primary" @click="csv">Download complete CSV</button></PageHeader><section class="panel filters"><label>From<input v-model="from" type="date"></label><label>To<input v-model="to" type="date"></label><label>Search inventory<input v-model="search" placeholder="Product, SKU, or category"></label><button class="btn primary" @click="load">Apply period</button></section><div class="stat-grid report-stats"><article class="stat"><span>Sales</span><strong>₱{{ money(data.sales?.total) }}</strong><small>{{ data.sales?.count || 0 }} transactions · VAT ₱{{ money(data.sales?.vat_amount) }}</small></article><article class="stat"><span>Orders</span><strong>{{ data.orders_summary?.count || 0 }}</strong><small>{{ data.orders_summary?.pending || 0 }} open · ₱{{ money(data.orders_summary?.value) }}</small></article><article class="stat"><span>Attendance</span><strong>{{ data.attendance_summary?.records || 0 }}</strong><small>{{ data.attendance_summary?.employees || 0 }} employees represented</small></article><article class="stat"><span>Finalized payroll</span><strong>₱{{ money(data.payroll?.net_total) }}</strong><small>{{ data.payroll?.runs?.length || 0 }} payroll snapshots</small></article><article class="stat"><span>Inventory value</span><strong>₱{{ money(data.inventory_summary?.value) }}</strong><small>{{ data.inventory_summary?.low_stock || 0 }} low-stock products</small></article><article class="stat"><span>Active workforce</span><strong>{{ data.employees?.active || 0 }}</strong><small>Current employees</small></article></div>
<div class="two-col report-columns"><section class="panel table-wrap"><div class="panel-head"><h2>Order statistics</h2></div><table><thead><tr><th>Status</th><th>Orders</th><th>Value</th></tr></thead><tbody><tr v-for="row in data.orders || []" :key="row.status"><td data-label="Status"><span class="tag">{{ row.status }}</span></td><td data-label="Orders">{{ row.count }}</td><td data-label="Value">₱{{ money(row.total) }}</td></tr><tr v-if="!data.orders?.length" class="empty-row"><td colspan="3">No orders in this period.</td></tr></tbody></table></section><section class="panel table-wrap"><div class="panel-head"><h2>Attendance statistics</h2></div><table><thead><tr><th>Status</th><th>Records</th></tr></thead><tbody><tr v-for="row in data.attendance || []" :key="row.status"><td data-label="Status"><span class="tag">{{ row.status }}</span></td><td data-label="Records">{{ row.count }}</td></tr><tr v-if="!data.attendance?.length" class="empty-row"><td colspan="2">No attendance in this period.</td></tr></tbody></table></section></div>
<section class="panel table-wrap"><div class="panel-head"><div><h2>Finalized payroll snapshots</h2><small>These are the records created by Finalize Payroll Run.</small></div></div><table><thead><tr><th>Reference</th><th>Period</th><th>Employees</th><th>Gross</th><th>Net</th><th>Finalized by</th><th>Finalized</th></tr></thead><tbody><tr v-for="run in data.payroll?.runs || []" :key="run.id"><td data-label="Reference"><strong>{{ run.reference }}</strong></td><td data-label="Period">{{ run.period_start }} – {{ run.period_end }}</td><td data-label="Employees">{{ run.items_count }}</td><td data-label="Gross">₱{{ money(run.gross_pay) }}</td><td data-label="Net">₱{{ money(run.net_pay) }}</td><td data-label="Finalized by">{{ run.creator?.name }}</td><td data-label="Finalized">{{ dateTime(run.finalized_at) }}</td></tr><tr v-if="!data.payroll?.runs?.length" class="empty-row"><td colspan="7">No finalized payroll runs in this period.</td></tr></tbody></table></section>
<section class="panel table-wrap"><div class="panel-head"><div><h2>Inventory statistics</h2><small>{{ filteredInventory.length }} matching products</small></div></div><table><thead><tr><th>Product</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Value</th></tr></thead><tbody><tr v-for="product in filteredInventory" :key="product.id"><td data-label="Product"><strong>{{ product.name }}</strong><small>{{ product.sku }} · {{ product.category }}</small></td><td data-label="On hand">{{ product.stock_quantity }}</td><td data-label="Reserved">{{ product.reserved_quantity }}</td><td data-label="Available">{{ product.available_quantity }}</td><td data-label="Value">₱{{ money(product.stock_quantity * product.price) }}</td></tr></tbody></table></section></template>
