<script setup>
import {computed,onMounted,ref,watch} from 'vue';import axios from 'axios';import {useAuthStore} from '../stores/auth';import {useRouter} from 'vue-router';
const auth=useAuthStore(),router=useRouter(),products=ref([]),category=ref('All'),cart=ref(JSON.parse(localStorage.getItem('nenial-cart')||'[]')),loading=ref(true),notice=ref('');const categories=['All','Materials','Aggregates','Tools','Safety','Finishing'];let checkoutKey=null;watch(cart,value=>localStorage.setItem('nenial-cart',JSON.stringify(value)),{deep:true});
const visible=computed(()=>category.value==='All'?products.value:products.value.filter(p=>p.category===category.value));const total=computed(()=>cart.value.reduce((s,i)=>s+i.price*i.quantity*(1-i.discount_percent/100),0));
onMounted(async()=>{try{products.value=(await axios.get('/api/storefront/products')).data.data}catch{notice.value='Storefront is temporarily unavailable.'}finally{loading.value=false}});
function add(p){const i=cart.value.find(x=>x.id===p.id);const qty=(i?.quantity||0)+1;if(qty>p.available_quantity)return notice.value='No more available stock.';i?i.quantity++:cart.value.push({...p,quantity:1});checkoutKey=null;notice.value=p.name+' added.';}
async function checkout(){if(!auth.authenticated)return router.push({path:'/login',query:{redirect:'/'}});if(auth.role!=='user')return notice.value='Online checkout requires a customer account.';checkoutKey||=crypto.randomUUID();try{await axios.post('/api/orders',{items:cart.value.map(i=>({product_id:i.id,quantity:i.quantity})),payment_method:'protected_payment',idempotency_key:checkoutKey});cart.value=[];checkoutKey=null;router.push('/app/orders')}catch(e){notice.value=e.response?.data?.message||'Checkout failed.'}}
</script>
<template><div class="store"><header class="store-nav"><a class="brand" href="#"><img src="/media/Nenial.jpg"><span>Nenial</span></a><nav><button v-for="c in categories" :class="{active:category===c}" @click="category=c">{{c}}</button></nav><div><RouterLink class="btn ghost" :to="auth.authenticated?'/app/dashboard':'/login'">{{auth.authenticated?'Dashboard':'Sign in'}}</RouterLink><button class="btn primary" :disabled="!cart.length" @click="checkout">Cart · {{cart.length}}</button></div></header><section class="store-hero"><div><span class="eyebrow">Construction supply, connected</span><h1>Materials in stock. Operations in sync.</h1><p>Shop live inventory with protected payment and delivery confirmation.</p><a class="btn light" href="#catalog">Browse catalog</a></div></section><main id="catalog" class="catalog"><div class="section-title"><div><span class="eyebrow">{{category}} catalog</span><h2>Available products</h2></div><strong>{{products.length}} live SKUs</strong></div><p v-if="notice" class="notice">{{notice}}</p><div v-if="loading" class="empty">Loading current inventory…</div><div class="product-grid"><article v-for="p in visible" :key="p.id" class="product-card"><div class="product-image"><img :src="p.image_url||'/media/Background.jpg'" :alt="p.name"></div><span class="tag">{{p.category}}</span><h3>{{p.name}}</h3><p>{{p.supplier}} · {{p.sku}}</p><div class="product-bottom"><strong>₱{{Number(p.price).toLocaleString()}}</strong><small :class="{low:p.is_low_stock}">{{p.available_quantity}} {{p.unit}}</small></div><button class="btn primary full" :disabled="p.available_quantity<1" @click="add(p)">{{p.available_quantity?'Add to cart':'Out of stock'}}</button></article></div></main><aside v-if="cart.length" class="cart-dock"><div><strong>{{cart.length}} products</strong><span>₱{{total.toLocaleString(undefined,{maximumFractionDigits:2})}}</span></div><button class="btn primary" @click="checkout">Protected checkout</button></aside></div></template>
